# Generated by Django 4.1.7 on 2023-03-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_car_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Cars'},
        ),
    ]
