# Generated by Django 4.1.7 on 2023-03-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_car_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='dor_num',
            new_name='door_num',
        ),
    ]
